export const mockInterviews16 = [
  {
    id: "int-1",
    candidateName: "Sarah Chen",
    candidateEmail: "sarah.chen@example.com",
    avatarBg: "bg-blue-600",
    jobRole: "Senior Frontend Engineer",
    category: "Software Engineering",
    atsScore: 96,
    matchScore: 94,
    round: "Technical Round 2",
    interviewer: "Alex Mercer (Tech Lead)",
    date: "2026-07-25",
    time: "10:00 AM",
    duration: "60 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/abc-defg-hij",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2, // 0: Application, 1: Screening, 2: Technical, 3: HR, 4: Final, 5: Offer
    notes: "Deep dive into React 19 concurrent features, virtual DOM diffing, and state architecture.",
    feedback: {
      technicalRating: 5,
      communicationRating: 5,
      problemSolvingRating: 4,
      cultureFitRating: 5,
      comments: "Outstanding technical candidate. Deep understanding of frontend performance and modern web design.",
      recommendation: "Strong Hire",
    },
  },
  {
    id: "int-2",
    candidateName: "Marcus Vance",
    candidateEmail: "marcus.vance@example.com",
    avatarBg: "bg-purple-600",
    jobRole: "ML Engineer",
    category: "Data Science & AI",
    atsScore: 94,
    matchScore: 92,
    round: "System Design",
    interviewer: "Dr. Elena Vance (Head of AI)",
    date: "2026-07-25",
    time: "02:00 PM",
    duration: "60 mins",
    mode: "Zoom",
    meetingLink: "https://zoom.us/j/9876543210",
    location: "Online",
    status: "Scheduled",
    stageIndex: 3,
    notes: "Evaluate scalable vector database architectures and LLM prompt engineering pipelines.",
    feedback: {
      technicalRating: 5,
      communicationRating: 4,
      problemSolvingRating: 5,
      cultureFitRating: 4,
      comments: "Exceptional machine learning background. High performance on vector search algorithms.",
      recommendation: "Strong Hire",
    },
  },
  {
    id: "int-3",
    candidateName: "Sophia Martinez",
    candidateEmail: "sophia.m@example.com",
    avatarBg: "bg-teal-600",
    jobRole: "Senior Frontend Engineer",
    category: "Software Engineering",
    atsScore: 93,
    matchScore: 91,
    round: "Final Executive Round",
    interviewer: "David Miller (VP of Eng)",
    date: "2026-07-24",
    time: "11:30 AM",
    duration: "45 mins",
    mode: "Microsoft Teams",
    meetingLink: "https://teams.microsoft.com/l/meetup",
    location: "Online",
    status: "Completed",
    stageIndex: 4,
    notes: "Executive leadership review, culture fit alignment, and product vision discussion.",
    feedback: {
      technicalRating: 5,
      communicationRating: 5,
      problemSolvingRating: 5,
      cultureFitRating: 5,
      comments: "Fantastic candidate for team lead expansion. Great vision and execution.",
      recommendation: "Strong Hire",
    },
  },
  {
    id: "int-4",
    candidateName: "Elena Rostova",
    candidateEmail: "elena.r@example.com",
    avatarBg: "bg-emerald-600",
    jobRole: "UI/UX Designer",
    category: "Product & UI/UX Design",
    atsScore: 88,
    matchScore: 86,
    round: "Portfolio Review",
    interviewer: "Chloe Bennett (Design Lead)",
    date: "2026-07-24",
    time: "03:30 PM",
    duration: "60 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/xyz-uvwx-rst",
    location: "Online",
    status: "Completed",
    stageIndex: 5,
    notes: "Review tokenized design systems, Figma component libraries, and user research case studies.",
    feedback: {
      technicalRating: 4,
      communicationRating: 5,
      problemSolvingRating: 4,
      cultureFitRating: 5,
      comments: "Hired. Excellent portfolio presentation and user-centric design approach.",
      recommendation: "Hire",
    },
  },
  {
    id: "int-5",
    candidateName: "David Kim",
    candidateEmail: "david.kim@example.com",
    avatarBg: "bg-amber-600",
    jobRole: "DevOps Engineer",
    category: "DevOps & Cloud",
    atsScore: 85,
    matchScore: 84,
    round: "Infrastructure Round",
    interviewer: "James Wilson (DevOps Lead)",
    date: "2026-07-26",
    time: "01:00 PM",
    duration: "45 mins",
    mode: "Zoom",
    meetingLink: "https://zoom.us/j/1234567890",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2,
    notes: "Test Kubernetes cluster zero-downtime rolling updates and Terraform automation scripts.",
    feedback: null,
  },
  {
    id: "int-6",
    candidateName: "Aisha Patel",
    candidateEmail: "aisha.patel@example.com",
    avatarBg: "bg-cyan-600",
    jobRole: "Software Engineer",
    category: "Software Engineering",
    atsScore: 81,
    matchScore: 80,
    round: "Screening Interview",
    interviewer: "Tanya Bhadana (Recruiter)",
    date: "2026-07-23",
    time: "04:00 PM",
    duration: "30 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/pqr-stuv-wxy",
    location: "Online",
    status: "Completed",
    stageIndex: 1,
    notes: "Initial salary expectations check, work authorization, and project experience review.",
    feedback: {
      technicalRating: 4,
      communicationRating: 4,
      problemSolvingRating: 4,
      cultureFitRating: 4,
      comments: "Solid mid-level developer. Passed screening and advancing to technical round.",
      recommendation: "Hire",
    },
  },
  {
    id: "int-7",
    candidateName: "Jonathan Hayes",
    candidateEmail: "j.hayes@example.com",
    avatarBg: "bg-rose-600",
    jobRole: "Product Manager",
    category: "Product Management",
    atsScore: 78,
    matchScore: 76,
    round: "Product Case Study",
    interviewer: "Samantha Reed (CPO)",
    date: "2026-07-26",
    time: "11:00 AM",
    duration: "60 mins",
    mode: "Microsoft Teams",
    meetingLink: "https://teams.microsoft.com/l/meetup2",
    location: "Online",
    status: "Rescheduled",
    stageIndex: 2,
    notes: "Rescheduled from July 23 upon candidate request due to business travel.",
    feedback: null,
  },
  {
    id: "int-8",
    candidateName: "Rachel Zhang",
    candidateEmail: "rachel.z@example.com",
    avatarBg: "bg-indigo-600",
    jobRole: "Data Scientist",
    category: "Data Science & AI",
    atsScore: 74,
    matchScore: 72,
    round: "Technical Coding",
    interviewer: "Dr. Mark Vance",
    date: "2026-07-22",
    time: "02:30 PM",
    duration: "45 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/ds-123-456",
    location: "Online",
    status: "Completed",
    stageIndex: 2,
    notes: "SQL query optimization and Python data manipulation test.",
    feedback: {
      technicalRating: 3,
      communicationRating: 4,
      problemSolvingRating: 3,
      cultureFitRating: 4,
      comments: "Good statistical foundation, but needs more deep learning project experience.",
      recommendation: "Hold",
    },
  },
  {
    id: "int-9",
    candidateName: "Michael Brown",
    candidateEmail: "mbrown@example.com",
    avatarBg: "bg-slate-700",
    jobRole: "DevOps Engineer",
    category: "DevOps & Cloud",
    atsScore: 68,
    matchScore: 65,
    round: "Screening Interview",
    interviewer: "Tanya Bhadana",
    date: "2026-07-21",
    time: "10:30 AM",
    duration: "30 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/mb-789-012",
    location: "Online",
    status: "Cancelled",
    stageIndex: 1,
    notes: "Cancelled - Candidate accepted another job offer prior to interview.",
    feedback: null,
  },
  {
    id: "int-10",
    candidateName: "Liam O'Connor",
    candidateEmail: "liam.oc@example.com",
    avatarBg: "bg-orange-600",
    jobRole: "AI Engineer",
    category: "Data Science & AI",
    atsScore: 89,
    matchScore: 88,
    round: "Technical Deep Dive",
    interviewer: "Dr. Elena Vance",
    date: "2026-07-27",
    time: "03:00 PM",
    duration: "60 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/lo-345-678",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2,
    notes: "Review computer vision model architecture and PyTorch optimization.",
    feedback: null,
  },
  {
    id: "int-11",
    candidateName: "Chloe Dubois",
    candidateEmail: "chloe.d@example.com",
    avatarBg: "bg-pink-600",
    jobRole: "UI/UX Designer",
    category: "Product & UI/UX Design",
    atsScore: 86,
    matchScore: 85,
    round: "Design Challenge",
    interviewer: "Chloe Bennett",
    date: "2026-07-27",
    time: "10:00 AM",
    duration: "60 mins",
    mode: "Zoom",
    meetingLink: "https://zoom.us/j/555666777",
    location: "Online",
    status: "Scheduled",
    stageIndex: 3,
    notes: "Interactive prototype walk-through and accessibility design review.",
    feedback: null,
  },
  {
    id: "int-12",
    candidateName: "Vikram Malhotra",
    email: "vikram.m@example.com",
    avatarBg: "bg-blue-700",
    jobRole: "Backend Engineer",
    category: "Software Engineering",
    atsScore: 82,
    matchScore: 81,
    round: "Technical Round 1",
    interviewer: "Alex Mercer",
    date: "2026-07-28",
    time: "11:00 AM",
    duration: "60 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/vm-999-888",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2,
    notes: "Java Spring Boot microservices concurrency and Kafka event processing test.",
    feedback: null,
  },
  {
    id: "int-13",
    candidateName: "Hannah Abbot",
    candidateEmail: "hannah.a@example.com",
    avatarBg: "bg-emerald-700",
    jobRole: "Product Manager",
    category: "Product Management",
    atsScore: 91,
    matchScore: 89,
    round: "Executive Review",
    interviewer: "Samantha Reed",
    date: "2026-07-20",
    time: "02:00 PM",
    duration: "45 mins",
    mode: "Offline",
    meetingLink: "N/A",
    location: "SF HQ - Conference Room A",
    status: "Completed",
    stageIndex: 5,
    notes: "Onsite final interview round. Offer extended and accepted.",
    feedback: {
      technicalRating: 5,
      communicationRating: 5,
      problemSolvingRating: 5,
      cultureFitRating: 5,
      comments: "Outstanding executive candidate. Offer extended.",
      recommendation: "Strong Hire",
    },
  },
  {
    id: "int-14",
    candidateName: "Ethan Wright",
    candidateEmail: "ethan.w@example.com",
    avatarBg: "bg-purple-700",
    jobRole: "Cloud Engineer",
    category: "DevOps & Cloud",
    atsScore: 79,
    matchScore: 77,
    round: "Technical Round 1",
    interviewer: "James Wilson",
    date: "2026-07-28",
    time: "02:30 PM",
    duration: "45 mins",
    mode: "Microsoft Teams",
    meetingLink: "https://teams.microsoft.com/l/meetup3",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2,
    notes: "AWS CloudFormation & Ansible automation test.",
    feedback: null,
  },
  {
    id: "int-15",
    candidateName: "Isabella Rossi",
    candidateEmail: "isabella.r@example.com",
    avatarBg: "bg-rose-700",
    jobRole: "Software Engineer",
    category: "Software Engineering",
    atsScore: 71,
    matchScore: 69,
    round: "Screening Interview",
    interviewer: "Tanya Bhadana",
    date: "2026-07-19",
    time: "11:00 AM",
    duration: "30 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/ir-111-222",
    location: "Online",
    status: "Completed",
    stageIndex: 1,
    notes: "Junior role fit screening.",
    feedback: {
      technicalRating: 2,
      communicationRating: 3,
      problemSolvingRating: 2,
      cultureFitRating: 4,
      comments: "Needs more production experience before senior engineering role.",
      recommendation: "Reject",
    },
  },
  {
    id: "int-16",
    candidateName: "Carlos Rivera",
    candidateEmail: "carlos.r@example.com",
    avatarBg: "bg-amber-700",
    jobRole: "Frontend Engineer",
    category: "Software Engineering",
    atsScore: 73,
    matchScore: 71,
    round: "Technical Round 1",
    interviewer: "Alex Mercer",
    date: "2026-07-29",
    time: "04:00 PM",
    duration: "45 mins",
    mode: "Google Meet",
    meetingLink: "https://meet.google.com/cr-333-444",
    location: "Online",
    status: "Scheduled",
    stageIndex: 2,
    notes: "Basic React component architecture and CSS layout test.",
    feedback: null,
  },
];
