import React from "react";
import Card from "../common/Card";
import { FaRobot, FaCheckCircle, FaStar } from "react-icons/fa";

function RecommendationCard({
  recommendation = "Excellent candidate for this role. Highly suitable for this position. Would recommend scheduling a technical interview.",
}) {
  return (
    <Card
      title="AI Recommendation"
      subtitle="Executive candidate assessment generated by HireSmart AI"
      headerBorder
      action={
        <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-bold border border-blue-200">
          AI Decision Engine
        </span>
      }
    >
      <div className="p-4 bg-slate-50 rounded-2xl border border-slate-200/80 flex items-start gap-4">
        {/* Icon Container: light green bg, emerald icon */}
        <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center text-lg shrink-0 border border-emerald-100 shadow-2xs">
          <FaRobot />
        </div>

        <div className="space-y-2 flex-1">
          <div className="flex items-center gap-2">
            {/* Title: Dark slate-900, font-bold */}
            <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              AI Decision Engine Verdict
            </h4>
            {/* Recommendation badge: green bg, text-emerald-700, border-emerald-300 */}
            <span className="text-[10px] bg-emerald-50 text-emerald-700 font-bold px-2.5 py-0.5 rounded-full border border-emerald-300">
              Strong Hire
            </span>
          </div>

          {/* Quote text */}
          <p className="text-xs sm:text-sm font-semibold text-slate-900 leading-relaxed">
            "{recommendation}"
          </p>

          {/* Description & Highlighted Values */}
          <div className="flex items-center gap-4 text-xs text-slate-600 pt-1">
            <span className="flex items-center gap-1 font-medium text-slate-600">
              <FaCheckCircle className="text-emerald-600 text-xs" />
              High Match Probability
            </span>
            <span className="flex items-center gap-1 font-medium text-slate-600">
              <FaStar className="text-amber-500 text-xs" />
              <strong className="text-emerald-600 font-semibold">
                94% vector match confidence
              </strong>
            </span>
          </div>
        </div>
      </div>
    </Card>
  );
}

export default RecommendationCard;
