export const mockRanking20 = [
  {
    id: "rank-1",
    rank: 1,
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    avatarBg: "bg-blue-600",
    category: "Software Engineering",
    atsScore: 96,
    matchScore: 94,
    overallScore: 95,
    experience: "6 Years",
    recommendation: "Highly Recommended",
    skills: ["React 19", "TypeScript", "Tailwind CSS", "Next.js", "Redux", "FastAPI"],
    missingSkills: ["Docker", "AWS"],
    whyRanked: "Top 1% score. Exceptional React architecture skills & 94% vector match.",
    summary: "Senior Fullstack Developer with strong frontend and AI vector search integration experience.",
    strengths: ["Clean state management", "Fast execution speed", "Production SaaS experience"],
    weaknesses: ["Needs minor cloud deployment refresh"],
    projects: 5,
  },
  {
    id: "rank-2",
    rank: 2,
    name: "Marcus Vance",
    email: "marcus.vance@example.com",
    avatarBg: "bg-purple-600",
    category: "Data Science & AI",
    atsScore: 94,
    matchScore: 92,
    overallScore: 93,
    experience: "8 Years",
    recommendation: "Highly Recommended",
    skills: ["Python", "PyTorch", "LLMs", "LangChain", "Vector DBs", "FastAPI"],
    missingSkills: ["Kubernetes", "GraphQL"],
    whyRanked: "Outstanding AI model fine-tuning & LLM pipeline design.",
    summary: "AI Researcher & Machine Learning Engineer specializing in RAG architectures.",
    strengths: ["Deep learning expertise", "Scalable vector search", "High publication count"],
    weaknesses: ["Lacks traditional UI frontend experience"],
    projects: 8,
  },
  {
    id: "rank-3",
    rank: 3,
    name: "Sophia Martinez",
    email: "sophia.m@example.com",
    avatarBg: "bg-teal-600",
    category: "Software Engineering",
    atsScore: 93,
    matchScore: 91,
    overallScore: 92,
    experience: "7 Years",
    recommendation: "Highly Recommended",
    skills: ["React", "TypeScript", "GraphQL", "Redux Toolkit", "Jest", "Webpack"],
    missingSkills: ["Python", "SQL"],
    whyRanked: "Proven enterprise UI architecture & high unit test coverage.",
    summary: "Senior Frontend Specialist with extensive experience in scalable design systems.",
    strengths: ["Component modularity", "Performance optimization"],
    weaknesses: ["Limited backend API experience"],
    projects: 9,
  },
  {
    id: "rank-4",
    rank: 4,
    name: "Hannah Abbot",
    email: "hannah.a@example.com",
    avatarBg: "bg-emerald-700",
    category: "Product Management",
    atsScore: 91,
    matchScore: 89,
    overallScore: 90,
    experience: "8 Years",
    recommendation: "Highly Recommended",
    skills: ["Product Roadmap", "Growth Hacking", "A/B Testing", "Mixpanel", "SQL"],
    missingSkills: ["Python", "Docker"],
    whyRanked: "Proven 40% user retention growth & strong cross-team leadership.",
    summary: "Lead Product Manager with track record scaling B2B SaaS applications.",
    strengths: ["Data-driven prioritization", "Executive stakeholder communication"],
    weaknesses: ["Does not write production code"],
    projects: 6,
  },
  {
    id: "rank-5",
    rank: 5,
    name: "Liam O'Connor",
    email: "liam.oc@example.com",
    avatarBg: "bg-orange-600",
    category: "Data Science & AI",
    atsScore: 89,
    matchScore: 88,
    overallScore: 88,
    experience: "5 Years",
    recommendation: "Highly Recommended",
    skills: ["PyTorch", "TensorFlow", "Computer Vision", "Python", "Docker", "OpenCV"],
    missingSkills: ["React", "TypeScript"],
    whyRanked: "High research caliber ML Scientist with 6 published computer vision models.",
    summary: "Computer Vision Scientist building real-time object detection models.",
    strengths: ["Mathematical algorithm optimization", "GPU acceleration"],
    weaknesses: ["Limited web front-end tooling"],
    projects: 6,
  },
  {
    id: "rank-6",
    rank: 6,
    name: "Elena Rostova",
    email: "elena.r@example.com",
    avatarBg: "bg-emerald-600",
    category: "Product & UI/UX Design",
    atsScore: 88,
    matchScore: 86,
    overallScore: 87,
    experience: "5 Years",
    recommendation: "Highly Recommended",
    skills: ["Figma", "UI/UX Design", "Design Systems", "Prototyping", "User Research"],
    missingSkills: ["React", "CSS"],
    whyRanked: "Built 4 multi-platform design systems with high accessibility standards.",
    summary: "Lead Product Designer specializing in complex B2B workflow design.",
    strengths: ["Tokenized design systems", "In-depth user research"],
    weaknesses: ["No production code writing"],
    projects: 4,
  },
  {
    id: "rank-7",
    rank: 7,
    name: "Chloe Dubois",
    email: "chloe.d@example.com",
    avatarBg: "bg-pink-600",
    category: "Product & UI/UX Design",
    atsScore: 86,
    matchScore: 85,
    overallScore: 85,
    experience: "6 Years",
    recommendation: "Recommended",
    skills: ["Figma", "User Journey Mapping", "Wireframing", "HCI", "Accessibility"],
    missingSkills: ["Frontend Code"],
    whyRanked: "Accessible UX workflows & clean visual hierarchy design.",
    summary: "Senior UX Designer focused on recruiter SaaS user experience.",
    strengths: ["Information architecture", "Accessibility compliance"],
    weaknesses: ["Motion design animations"],
    projects: 5,
  },
  {
    id: "rank-8",
    rank: 8,
    name: "David Kim",
    email: "david.kim@example.com",
    avatarBg: "bg-amber-600",
    category: "DevOps & Cloud",
    atsScore: 85,
    matchScore: 84,
    overallScore: 84,
    experience: "7 Years",
    recommendation: "Recommended",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD", "Bash"],
    missingSkills: ["Python", "React"],
    whyRanked: "Zero-downtime Kubernetes deployment automation history.",
    summary: "DevOps Architect specializing in AWS multi-region infrastructure.",
    strengths: ["Infrastructure-as-code", "Automated failover"],
    weaknesses: ["Limited GCP experience"],
    projects: 12,
  },
  {
    id: "rank-9",
    rank: 9,
    name: "Vikram Malhotra",
    email: "vikram.m@example.com",
    avatarBg: "bg-blue-700",
    category: "Software Engineering",
    atsScore: 82,
    matchScore: 81,
    overallScore: 81,
    experience: "5 Years",
    recommendation: "Recommended",
    skills: ["Java", "Spring Boot", "PostgreSQL", "Kafka", "Microservices", "Docker"],
    missingSkills: ["React", "TypeScript"],
    whyRanked: "High-concurrency backend services & Kafka streaming expertise.",
    summary: "Backend Engineer building distributed high-throughput microservices.",
    strengths: ["Database scaling", "Kafka event streaming"],
    weaknesses: ["No modern React experience"],
    projects: 7,
  },
  {
    id: "rank-10",
    rank: 10,
    name: "Aisha Patel",
    email: "aisha.patel@example.com",
    avatarBg: "bg-cyan-600",
    category: "Software Engineering",
    atsScore: 81,
    matchScore: 80,
    overallScore: 80,
    experience: "4 Years",
    recommendation: "Recommended",
    skills: ["Node.js", "Express", "React", "MongoDB", "JavaScript", "REST APIs"],
    missingSkills: ["TypeScript", "AWS"],
    whyRanked: "Fast REST API endpoint development & clean microservice design.",
    summary: "Fullstack Web Developer with focus on Node.js backends.",
    strengths: ["Rapid API development", "Clean code structure"],
    weaknesses: ["Lacks TypeScript proficiency"],
    projects: 6,
  },
  {
    id: "rank-11",
    rank: 11,
    name: "Ethan Wright",
    email: "ethan.w@example.com",
    avatarBg: "bg-purple-700",
    category: "DevOps & Cloud",
    atsScore: 79,
    matchScore: 77,
    overallScore: 78,
    experience: "4 Years",
    recommendation: "Consider",
    skills: ["AWS", "Docker", "Ansible", "CI/CD Pipelines", "Python", "Prometheus"],
    missingSkills: ["Kubernetes", "Terraform"],
    whyRanked: "Solid monitoring & alerting automation setup.",
    summary: "Cloud Operations Engineer managing AWS infrastructure.",
    strengths: ["Prometheus monitoring", "Ansible playbooks"],
    weaknesses: ["Kubernetes cluster administration"],
    projects: 4,
  },
  {
    id: "rank-12",
    rank: 12,
    name: "Jonathan Hayes",
    email: "j.hayes@example.com",
    avatarBg: "bg-rose-600",
    category: "Product Management",
    atsScore: 78,
    matchScore: 76,
    overallScore: 77,
    experience: "6 Years",
    recommendation: "Consider",
    skills: ["Product Strategy", "Agile/Scrum", "Jira", "Data Analytics", "Roadmapping"],
    missingSkills: ["SQL", "Coding"],
    whyRanked: "Cross-functional team leadership & Agile backlog management.",
    summary: "Technical PM with MBA background.",
    strengths: ["Sprint planning", "User story mapping"],
    weaknesses: ["Basic technical query skills"],
    projects: 3,
  },
  {
    id: "rank-13",
    rank: 13,
    name: "Rachel Zhang",
    email: "rachel.z@example.com",
    avatarBg: "bg-indigo-600",
    category: "Data Science & AI",
    atsScore: 74,
    matchScore: 72,
    overallScore: 73,
    experience: "3 Years",
    recommendation: "Consider",
    skills: ["Python", "SQL", "Pandas", "Scikit-Learn", "Tableau", "Data Analysis"],
    missingSkills: ["PyTorch", "LLMs"],
    whyRanked: "Good statistical modeling & BI dashboard design.",
    summary: "Data Analyst transitioning to Machine Learning roles.",
    strengths: ["SQL query optimization", "Data visualization"],
    weaknesses: ["Deep learning frameworks"],
    projects: 4,
  },
  {
    id: "rank-14",
    rank: 14,
    name: "Carlos Rivera",
    email: "carlos.r@example.com",
    avatarBg: "bg-amber-700",
    category: "Software Engineering",
    atsScore: 73,
    matchScore: 71,
    overallScore: 72,
    experience: "3 Years",
    recommendation: "Consider",
    skills: ["JavaScript", "React", "HTML/CSS", "Git", "Bootstrap"],
    missingSkills: ["TypeScript", "Next.js", "Backend"],
    whyRanked: "Solid junior-mid frontend developer with clean code hygiene.",
    summary: "Frontend Developer focusing on React web components.",
    strengths: ["Fast learner", "Clean CSS styling"],
    weaknesses: ["No backend or cloud experience"],
    projects: 3,
  },
  {
    id: "rank-15",
    rank: 15,
    name: "Isabella Rossi",
    email: "isabella.r@example.com",
    avatarBg: "bg-rose-700",
    category: "Software Engineering",
    atsScore: 71,
    matchScore: 69,
    overallScore: 70,
    experience: "2 Years",
    recommendation: "Consider",
    skills: ["JavaScript", "HTML/CSS", "React", "Git"],
    missingSkills: ["TypeScript", "Python", "SQL"],
    whyRanked: "Junior developer eager to learn; good foundational HTML/JS.",
    summary: "Junior Web Developer.",
    strengths: ["High enthusiasm", "Bootcamp top graduate"],
    weaknesses: ["Lacks senior architectural experience"],
    projects: 3,
  },
  {
    id: "rank-16",
    rank: 16,
    name: "Michael Brown",
    email: "mbrown@example.com",
    avatarBg: "bg-slate-700",
    category: "DevOps & Cloud",
    atsScore: 68,
    matchScore: 65,
    overallScore: 66,
    experience: "4 Years",
    recommendation: "Not Suitable",
    skills: ["Linux", "Bash Scripting", "Networking", "Firewall Security"],
    missingSkills: ["AWS", "Docker", "Kubernetes", "CI/CD"],
    whyRanked: "Linux sysadmin background without cloud-native automation tooling.",
    summary: "Traditional System Administrator.",
    strengths: ["Linux kernel configuration"],
    weaknesses: ["Lacks cloud & DevOps toolchain"],
    projects: 2,
  },
  {
    id: "rank-17",
    rank: 17,
    name: "Kevin Patel",
    email: "kevin.p@example.com",
    avatarBg: "bg-blue-800",
    category: "Software Engineering",
    atsScore: 65,
    matchScore: 62,
    overallScore: 63,
    experience: "2 Years",
    recommendation: "Not Suitable",
    skills: ["C++", "Python", "Algorithms"],
    missingSkills: ["React", "Web Frameworks", "SQL"],
    whyRanked: "Strong competitive programming algorithms, but missing web stack.",
    summary: "CS Graduate focusing on algorithmic problem solving.",
    strengths: ["Data structures & algorithms"],
    weaknesses: ["No production web development experience"],
    projects: 1,
  },
  {
    id: "rank-18",
    rank: 18,
    name: "Amanda White",
    email: "amanda.w@example.com",
    avatarBg: "bg-pink-700",
    category: "Product & UI/UX Design",
    atsScore: 62,
    matchScore: 60,
    overallScore: 61,
    experience: "2 Years",
    recommendation: "Not Suitable",
    skills: ["Photoshop", "Illustrator", "Graphic Design"],
    missingSkills: ["Figma", "UI/UX", "Prototyping", "Design Systems"],
    whyRanked: "Graphic design background without modern Figma UI/UX software skills.",
    summary: "Graphic Designer transitioning to UX.",
    strengths: ["Visual branding & illustration"],
    weaknesses: ["Lacks interactive UI/UX software experience"],
    projects: 2,
  },
  {
    id: "rank-19",
    rank: 19,
    name: "Daniel Green",
    email: "d.green@example.com",
    avatarBg: "bg-emerald-800",
    category: "Data Science & AI",
    atsScore: 60,
    matchScore: 58,
    overallScore: 59,
    experience: "1 Year",
    recommendation: "Not Suitable",
    skills: ["Excel", "Python", "SQL Basics"],
    missingSkills: ["PyTorch", "TensorFlow", "Scikit-Learn", "LLMs"],
    whyRanked: "Entry level data entry & basic Excel automation.",
    summary: "Junior Data Clerk.",
    strengths: ["Data entry accuracy"],
    weaknesses: ["No machine learning background"],
    projects: 1,
  },
  {
    id: "rank-20",
    rank: 20,
    name: "Jessica Taylor",
    email: "jtaylor@example.com",
    avatarBg: "bg-slate-800",
    category: "Product Management",
    atsScore: 55,
    matchScore: 52,
    overallScore: 53,
    experience: "1 Year",
    recommendation: "Not Suitable",
    skills: ["MS Project", "Word", "PowerPoint"],
    missingSkills: ["Agile", "Jira", "Mixpanel", "SQL", "Product Strategy"],
    whyRanked: "Project coordinator background lacking product analytics tooling.",
    summary: "Project Coordinator.",
    strengths: ["Meeting coordination"],
    weaknesses: ["No technical product management experience"],
    projects: 1,
  },
];
