export const mockJobs12 = [
  {
    id: "job-1",
    title: "Senior Lead Frontend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$145,000 - $175,000",
    applications: 142,
    status: "Open",
    createdDate: "Jul 15, 2026",
    skills: ["React 19", "TypeScript", "Tailwind CSS", "Next.js", "Redux"],
    responsibilities:
      "Design and build responsive web applications using React, TypeScript, and Tailwind CSS. Collaborate with backend AI teams to integrate API endpoints and state management.",
    qualifications:
      "5+ years of professional React experience. Strong understanding of frontend architecture, component lifecycles, and web performance optimization.",
    benefits: "Full health/dental insurance, 401(k) matching, flexible remote days, $2,500 learning stipend.",
    aiSummary: "This position requires a Senior Frontend Lead with React, TypeScript, and modern SaaS design system experience.",
  },
  {
    id: "job-2",
    title: "Backend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Austin, TX",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$140,000 - $175,000",
    applications: 98,
    status: "Open",
    createdDate: "Jul 18, 2026",
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker", "REST APIs"],
    responsibilities:
      "Develop high-throughput asynchronous REST APIs using FastAPI and PostgreSQL. Implement Redis caching and microservice communication patterns.",
    qualifications:
      "5+ years with Python and relational database design. Experience with asynchronous I/O and query performance tuning.",
    benefits: "Unlimited PTO, top-tier health coverage, annual company retreat, home office allowance.",
    aiSummary: "This position requires a Python Backend Engineer with FastAPI, PostgreSQL, and high-concurrency microservice experience.",
  },
  {
    id: "job-3",
    title: "ML Engineer",
    company: "HireSmart AI",
    department: "AI & Data",
    location: "New York, NY",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$150,000 - $185,000",
    applications: 116,
    status: "Open",
    createdDate: "Jul 15, 2026",
    skills: ["PyTorch", "Python", "Scikit-Learn", "Vector DBs", "LangChain", "LLMs"],
    responsibilities:
      "Build and fine-tune machine learning and LLM vector embeddings for resume analysis and semantic candidate matching.",
    qualifications:
      "M.S. or B.S. in Computer Science/AI. Deep expertise in PyTorch, scikit-learn, and vector database retrieval.",
    benefits: "Stock options, comprehensive medical coverage, wellness stipend, tech equipment allowance.",
    aiSummary: "This position requires a Machine Learning Engineer specializing in NLP, vector embeddings, and LLM fine-tuning.",
  },
  {
    id: "job-4",
    title: "Data Scientist",
    company: "HireSmart AI",
    department: "AI & Data",
    location: "Boston, MA",
    workType: "Onsite",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$125,000 - $155,000",
    applications: 84,
    status: "Open",
    createdDate: "Jul 12, 2026",
    skills: ["Python", "SQL", "Pandas", "Statistical Modeling", "Tableau"],
    responsibilities:
      "Analyze recruitment data streams, compute predictive match scores, and create executive business intelligence dashboards.",
    qualifications:
      "Degree in Statistics or Data Science. Proficiency in SQL query optimization and statistical testing.",
    benefits: "Competitive salary, 401(k), health/vision, commuter benefits.",
    aiSummary: "This position requires a Data Scientist with expertise in predictive statistical modeling and SQL analytics.",
  },
  {
    id: "job-5",
    title: "DevOps Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Seattle, WA",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "5-8 Years",
    salaryRange: "$145,000 - $180,000",
    applications: 72,
    status: "Open",
    createdDate: "Jul 10, 2026",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD", "Prometheus"],
    responsibilities:
      "Manage AWS cloud infrastructure, Kubernetes clusters, and automated CI/CD deployment pipelines.",
    qualifications:
      "5+ years operating production Kubernetes infrastructure and infrastructure-as-code with Terraform.",
    benefits: "Full remote setup, health coverage, annual performance bonus.",
    aiSummary: "This position requires a Cloud DevOps Engineer with Kubernetes, AWS, and Terraform automation skills.",
  },
];

export const mockJobsWorkspace = {
  "job-1": {
    id: "job-1",
    title: "Senior Lead Frontend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "San Francisco, CA (Hybrid)",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$145,000 - $175,000",
    applications: 142,
    status: "Open",
    createdDate: "Jul 15, 2026",
    closingDate: "Aug 30, 2026",
    hiringManager: "Alex Mercer (Director of Engineering)",
    recruiter: "Tanya Bhadana (Senior Recruiter)",
    hiringGoal: "Fill 2 Senior Lead Frontend positions for Core SaaS & Design System squads",
    
    // Overview Tab Content
    description: `We are looking for a Senior Lead Frontend Engineer to architect high-performance React 19 micro-frontends, tokenized Tailwind CSS design systems, and TypeScript web applications for HireSmart AI. In this role, you will collaborate with backend AI teams, mentor junior developers, and drive frontend performance optimizations.`,
    
    skills: ["React 19", "TypeScript", "Tailwind CSS", "Next.js", "Redux Toolkit", "FastAPI", "Docker", "Jest"],
    
    responsibilities: [
      "Architect and maintain scalable React 19 micro-frontend applications for 500k+ monthly active recruiters.",
      "Lead and mentor a squad of 6 frontend software engineers, establishing code review and WCAG AAA standards.",
      "Collaborate with AI engineering teams to integrate real-time vector search and LLM resume analysis APIs.",
      "Optimize web build pipelines and client asset caching to maintain under 500ms core web vitals latency.",
      "Design and maintain tokenized component design system libraries with Tailwind CSS.",
    ],
    
    qualifications: [
      "5+ years of professional software engineering experience with React, TypeScript, and modern state management.",
      "Proven experience architecting micro-frontends or large-scale monorepo design systems.",
      "Strong proficiency in web performance debugging, memory leak resolution, and bundler internals (Vite / Webpack).",
      "B.S. or M.S. in Computer Science, Software Engineering, or equivalent quantitative field.",
    ],
    
    benefits: [
      "Competitive base salary ($145k-$175k) + generous equity package",
      "Full medical, dental, and vision insurance with 100% premium coverage",
      "401(k) retirement plan with 5% immediate company match",
      "Flexible hybrid work environment (2 days office, 3 days remote)",
      "$2,500 annual learning stipend for conferences & courses",
      "Unlimited PTO with mandatory 3-week minimum unplugged vacation",
    ],

    // Job Quality Breakdown
    qualityMetrics: {
      overallQualityScore: 95,
      keywordCoverage: { score: 96, label: "Excellent", explanation: "Covers 19 out of 20 high-value target industry keywords including React 19, TypeScript, and Micro-frontends." },
      roleClarity: { score: 94, label: "High Clarity", explanation: "Responsibilities and team structure are clearly delineated without ambiguous jargon." },
      skillCompleteness: { score: 98, label: "Complete", explanation: "Core technical, framework, and soft skill requirements are comprehensively specified." },
      experienceClarity: { score: 92, label: "Clear Criteria", explanation: "Experience bounds (5-7 years) and degree expectations are explicitly stated." },
      biasDetection: { score: 98, label: "Bias Free", explanation: "0 gender or demographic bias phrases detected. Neutral, inclusive enterprise wording." },
      estimatedCandidateReach: { score: 94, label: "~1,400 Candidates", explanation: "High search visibility across LinkedIn Recruiter, Indeed, and Google Jobs index." },
      improvementSuggestions: [
        "Mention specific CI/CD deployment tools (e.g. GitHub Actions / Docker) in qualifications.",
        "Add expected interview stage timeline to set clear candidate expectations up front.",
      ],
    },

    // Detailed Applicants List
    applicants: [
      {
        id: "cand-1",
        name: "Sarah Chen",
        photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=160&auto=format&fit=crop",
        role: "Senior Lead Frontend Engineer",
        company: "Acme Cloud SaaS",
        experience: "6 Years",
        matchScore: 94,
        atsScore: 96,
        stage: "Interview Scheduled",
        interviewStatus: "Tech Round 2",
        appliedDate: "Jul 20, 2026",
        email: "sarah.chen@example.com",
        location: "San Francisco, CA",
        education: "B.S. CS, Stanford",
        skills: ["React 19", "TypeScript", "Tailwind CSS", "FastAPI"],
        recommendation: "Strong Hire",
        summary: "Architected React 19 micro-frontend with 40% latency reduction. Managed team of 6 engineers.",
        strengths: ["React Architecture", "Design Systems", "Team Leadership"],
        weaknesses: ["Limited Kubernetes"],
      },
      {
        id: "cand-2",
        name: "Marcus Vance",
        photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=160&auto=format&fit=crop",
        role: "Staff Frontend Architect",
        company: "Vance Tech Labs",
        experience: "7 Years",
        matchScore: 92,
        atsScore: 94,
        stage: "Shortlisted",
        interviewStatus: "Screening Done",
        appliedDate: "Jul 19, 2026",
        email: "marcus.vance@example.com",
        location: "Oakland, CA",
        education: "M.S. CS, UC Berkeley",
        skills: ["React", "TypeScript", "Next.js", "GraphQL"],
        recommendation: "Strong Hire",
        summary: "7 years building high-throughput web apps and micro-frontends.",
        strengths: ["System Architecture", "Performance Tuning"],
        weaknesses: ["Secondary Python experience"],
      },
      {
        id: "cand-3",
        name: "Sophia Martinez",
        photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=160&auto=format&fit=crop",
        role: "React Tech Lead",
        company: "DesignScale Systems",
        experience: "6 Years",
        matchScore: 91,
        atsScore: 93,
        stage: "Interview Scheduled",
        interviewStatus: "System Design",
        appliedDate: "Jul 18, 2026",
        email: "sophia.m@example.com",
        location: "San Jose, CA",
        education: "B.S. Software Eng, MIT",
        skills: ["React", "TypeScript", "Redux", "Storybook"],
        recommendation: "Hire",
        summary: "Created enterprise accessibility design system adopted by 40+ products.",
        strengths: ["Design System Mastery", "Accessibility AAA"],
        weaknesses: ["No Docker exposure"],
      },
      {
        id: "cand-4",
        name: "David Kim",
        photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=160&auto=format&fit=crop",
        role: "Senior UI Engineer",
        company: "Apex Cloud Solutions",
        experience: "5 Years",
        matchScore: 88,
        atsScore: 90,
        stage: "Screened",
        interviewStatus: "Pending Schedule",
        appliedDate: "Jul 17, 2026",
        email: "david.kim@example.com",
        location: "San Francisco, CA",
        education: "B.S. CS, Carnegie Mellon",
        skills: ["React", "JavaScript", "Tailwind CSS", "Jest"],
        recommendation: "Hire",
        summary: "Built responsive SaaS dashboards serving 100k daily users.",
        strengths: ["Clean Code", "UI Precision"],
        weaknesses: ["Lacks lead experience"],
      },
      {
        id: "cand-5",
        name: "Aisha Patel",
        photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=160&auto=format&fit=crop",
        role: "Fullstack Frontend Engineer",
        company: "Innovate AI Labs",
        experience: "5 Years",
        matchScore: 86,
        atsScore: 89,
        stage: "Applied",
        interviewStatus: "Under Review",
        appliedDate: "Jul 16, 2026",
        email: "aisha.patel@example.com",
        location: "Remote (CA)",
        education: "B.S. CS, UCLA",
        skills: ["React", "TypeScript", "Node.js", "Express"],
        recommendation: "Maybe",
        summary: "Fullstack background with strong React and Node.js REST API skills.",
        strengths: ["Fullstack Versatility"],
        weaknesses: ["High salary expectation"],
      },
      {
        id: "cand-6",
        name: "Elena Rostova",
        photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=160&auto=format&fit=crop",
        role: "Senior Web Developer",
        company: "Global Tech Inc",
        experience: "6 Years",
        matchScore: 85,
        atsScore: 87,
        stage: "Final Round",
        interviewStatus: "Leadership Scheduled",
        appliedDate: "Jul 15, 2026",
        email: "elena.r@example.com",
        location: "San Francisco, CA",
        education: "M.S. CS, Cornell",
        skills: ["React 18", "TypeScript", "Next.js", "GraphQL"],
        recommendation: "Strong Hire",
        summary: "Lead web engineer for enterprise analytics platform.",
        strengths: ["React Mastery", "GraphQL Federation"],
        weaknesses: ["Notice period 45 days"],
      },
    ],

    // Job Timeline Events
    timelineEvents: [
      { id: "evt-1", title: "Job Created & Published", date: "Jul 15, 2026", user: "Tanya Bhadana", desc: "Position opened with budget approval ($145k-$175k)." },
      { id: "evt-2", title: "First 50 Applications Received", date: "Jul 17, 2026", user: "HireSmart AI Engine", desc: "Automated vector embedding parsing triggered for initial pool." },
      { id: "evt-3", title: "Top Candidates Shortlisted", date: "Jul 19, 2026", user: "Alex Mercer", desc: "12 candidates moved to priority tech screening stage." },
      { id: "evt-4", title: "Technical Interviews Commenced", date: "Jul 22, 2026", user: "David Miller", desc: "Scheduled 6 system design & coding interviews." },
      { id: "evt-5", title: "First Offer Package Prepared", date: "Jul 24, 2026", user: "Tanya Bhadana", desc: "Offer letter generated for Rachel Zhang ($165k base)." },
    ],

    // Interviews Section Data
    interviews: [
      {
        id: "int-1",
        candidateName: "Sarah Chen",
        candidatePhoto: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=160&auto=format&fit=crop",
        round: "System Design & Architecture",
        interviewer: "David Miller (Engineering Manager)",
        date: "Jul 24, 2026",
        time: "03:00 PM PST",
        rating: 5.0,
        status: "Completed",
        meetingLink: "https://meet.google.com/abc-defg-hij",
        feedback: "Exceptional mastery of React micro-frontend isolation and tokenized Tailwind CSS design systems.",
      },
      {
        id: "int-2",
        candidateName: "Sophia Martinez",
        candidatePhoto: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=160&auto=format&fit=crop",
        round: "Technical Coding Round 1",
        interviewer: "Alex Mercer (Tech Lead)",
        date: "Jul 26, 2026",
        time: "11:00 AM PST",
        rating: 4.8,
        status: "Scheduled",
        meetingLink: "https://meet.google.com/xyz-uvwx-rst",
        feedback: "Pending completion.",
      },
    ],

    // Job Intelligence Analytics
    insights: {
      totalApplications: 142,
      avgMatchScore: 88.4,
      avgAtsScore: 91.2,
      timeToHireAvgDays: 18,
      offerAcceptanceRate: 85,
      hiringVelocity: "14 Days (Fast Track)",
      topSkills: [
        { skill: "React 19 / 18", count: 128, percentage: 90 },
        { skill: "TypeScript", count: 122, percentage: 86 },
        { skill: "Tailwind CSS", count: 110, percentage: 77 },
        { skill: "Next.js", count: 95, percentage: 67 },
        { skill: "Redux / Zustand", count: 88, percentage: 62 },
        { skill: "Python FastAPI", count: 64, percentage: 45 },
      ],
      missingSkillsInPool: [
        { skill: "Kubernetes Operators", gap: "68% of candidates lack production K8s deployment experience." },
        { skill: "GraphQL Schema Federation", gap: "55% candidates use REST/OpenAPI rather than GraphQL." },
      ],
      universitySources: [
        { school: "Stanford University", candidates: 14 },
        { school: "UC Berkeley", candidates: 18 },
        { school: "CMU / MIT", candidates: 12 },
        { school: "San Jose State", candidates: 22 },
        { school: "Other Institutions", candidates: 76 },
      ],
      experienceDistribution: [
        { range: "1-3 Years", count: 18 },
        { range: "4-5 Years", count: 54 },
        { range: "6-7 Years", count: 52 },
        { range: "8+ Years", count: 18 },
      ],
      resumeSources: [
        { source: "LinkedIn Recruiter", count: 68 },
        { source: "Company Career Portal", count: 42 },
        { source: "Employee Referral", count: 20 },
        { source: "Indeed / Glassdoor", count: 12 },
      ],
      salaryDistribution: [
        { tier: "< $130k", count: 12 },
        { tier: "$130k - $150k", count: 58 },
        { tier: "$150k - $175k", count: 62 },
        { tier: "> $175k", count: 10 },
      ],
    },

    recentActivity: [
      { id: "act-1", user: "Tanya Bhadana", action: "Moved Sarah Chen to 'Interview Scheduled'", time: "2 hours ago" },
      { id: "act-2", user: "Alex Mercer", action: "Submitted 5.0 Rating for David Miller round", time: "4 hours ago" },
      { id: "act-3", user: "System Scheduler", action: "Sent calendar invite for Sophia Martinez", time: "Yesterday" },
      { id: "act-4", user: "HireSmart Vector Engine", action: "Parsed 8 new candidate resumes", time: "2 days ago" },
    ],
  },
};

export function getJobWorkspaceData(jobId) {
  if (mockJobsWorkspace[jobId]) {
    return mockJobsWorkspace[jobId];
  }
  
  const base = mockJobsWorkspace["job-1"];
  return {
    ...base,
    id: jobId,
    title: `Role ${jobId.replace("job-", "#")}`,
  };
}
