export const mockJobs18 = [
  // -------------------------------------------------------------
  // OPEN JOBS (8 Actively Hiring Roles)
  // -------------------------------------------------------------
  {
    id: "job-1",
    title: "Senior Lead Frontend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$145,000 - $175,000",
    applications: 142,
    matchScore: 94,
    status: "Open",
    createdDate: "Jul 15, 2026",
    lastUpdated: "2 hours ago",
    skills: ["React 19", "TypeScript", "Tailwind CSS", "Next.js", "Redux"],
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "High priority active opening requiring a Senior Frontend Lead with React 19 and design system expertise.",
  },
  {
    id: "job-2",
    title: "ML Engineer",
    company: "HireSmart AI",
    department: "AI & Data",
    location: "New York, NY",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$150,000 - $185,000",
    applications: 116,
    matchScore: 92,
    status: "Open",
    createdDate: "Jul 18, 2026",
    lastUpdated: "4 hours ago",
    skills: ["PyTorch", "Python", "Vector DBs", "LangChain", "LLMs"],
    hiringManager: "Dr. Aris Thorne",
    recruiter: "Tanya Bhadana",
    aiSummary: "Actively interviewing ML candidates for resume embedding parsing and LLM vector match.",
  },
  {
    id: "job-3",
    title: "Backend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Austin, TX",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$140,000 - $175,000",
    applications: 98,
    matchScore: 90,
    status: "Open",
    createdDate: "Jul 14, 2026",
    lastUpdated: "Yesterday",
    skills: ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker"],
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "High throughput backend REST API position supporting real-time candidate search.",
  },
  {
    id: "job-4",
    title: "DevOps Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Seattle, WA",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "5-8 Years",
    salaryRange: "$145,000 - $180,000",
    applications: 72,
    matchScore: 88,
    status: "Open",
    createdDate: "Jul 10, 2026",
    lastUpdated: "3 days ago",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD"],
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Production cloud infrastructure automation and zero-downtime Kubernetes management.",
  },
  {
    id: "job-5",
    title: "AI Research Engineer",
    company: "HireSmart AI",
    department: "AI & Data",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "4-6 Years",
    salaryRange: "$160,000 - $200,000",
    applications: 134,
    matchScore: 95,
    status: "Open",
    createdDate: "Jul 20, 2026",
    lastUpdated: "Just now",
    skills: ["PyTorch", "Transformers", "NLP", "Python", "Deep Learning"],
    hiringManager: "Dr. Aris Thorne",
    recruiter: "Tanya Bhadana",
    aiSummary: "Applied NLP research role focused on fine-tuning enterprise recruiting models.",
  },
  {
    id: "job-6",
    title: "Data Scientist",
    company: "HireSmart AI",
    department: "AI & Data",
    location: "Boston, MA",
    workType: "Onsite",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$125,000 - $155,000",
    applications: 84,
    matchScore: 86,
    status: "Open",
    createdDate: "Jul 12, 2026",
    lastUpdated: "5 days ago",
    skills: ["Python", "SQL", "Pandas", "Statistical Modeling", "Tableau"],
    hiringManager: "Dr. Aris Thorne",
    recruiter: "Tanya Bhadana",
    aiSummary: "Predictive candidate match metrics and recruiter analytics dashboard engineering.",
  },
  {
    id: "job-7",
    title: "Product Designer",
    company: "HireSmart AI",
    department: "Design",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "4-6 Years",
    salaryRange: "$130,000 - $160,000",
    applications: 92,
    matchScore: 89,
    status: "Open",
    createdDate: "Jul 08, 2026",
    lastUpdated: "1 week ago",
    skills: ["Figma", "UI/UX Design", "Design Systems", "Prototyping", "User Research"],
    hiringManager: "Elena Rostova",
    recruiter: "Tanya Bhadana",
    aiSummary: "Enterprise SaaS design systems and recruiter workspace UX architecture.",
  },
  {
    id: "job-8",
    title: "Cloud Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Denver, CO",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$135,000 - $165,000",
    applications: 64,
    matchScore: 87,
    status: "Open",
    createdDate: "Jul 05, 2026",
    lastUpdated: "1 week ago",
    skills: ["GCP", "Terraform", "Python", "Networking", "IAM Security"],
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Multi-cloud infrastructure migration and automated security policy enforcement.",
  },

  // -------------------------------------------------------------
  // DRAFT JOBS (4 Created but Not Published Roles)
  // -------------------------------------------------------------
  {
    id: "job-9",
    title: "Senior Flutter Developer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Remote",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "4-6 Years",
    salaryRange: "$130,000 - $160,000",
    applications: 0,
    matchScore: 0,
    status: "Draft",
    createdDate: "Jul 22, 2026",
    lastUpdated: "1 day ago",
    skills: ["Flutter", "Dart", "Cross-Platform", "REST APIs", "State Management"],
    note: "This role has not been published yet.",
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Draft requisition for upcoming mobile recruiter companion app.",
  },
  {
    id: "job-10",
    title: "Security Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$150,000 - $185,000",
    applications: 0,
    matchScore: 0,
    status: "Draft",
    createdDate: "Jul 21, 2026",
    lastUpdated: "2 days ago",
    skills: ["SOC2 Compliance", "Penetration Testing", "AWS Security", "OAuth 2.0"],
    note: "This role has not been published yet.",
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Draft requisition for enterprise cloud security and SOC2 compliance audit lead.",
  },
  {
    id: "job-11",
    title: "AI Product Manager",
    company: "HireSmart AI",
    department: "Product",
    location: "New York, NY",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "4-6 Years",
    salaryRange: "$155,000 - $190,000",
    applications: 0,
    matchScore: 0,
    status: "Draft",
    createdDate: "Jul 19, 2026",
    lastUpdated: "4 days ago",
    skills: ["Product Roadmap", "AI/ML Product Strategy", "User Research", "Metrics"],
    note: "This role has not been published yet.",
    hiringManager: "Jonathan Hayes",
    recruiter: "Tanya Bhadana",
    aiSummary: "Draft role awaiting executive headcount sign-off for Copilot product squad.",
  },
  {
    id: "job-12",
    title: "QA Automation Lead",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Austin, TX",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$120,000 - $145,000",
    applications: 0,
    matchScore: 0,
    status: "Draft",
    createdDate: "Jul 17, 2026",
    lastUpdated: "5 days ago",
    skills: ["Playwright", "Cypress", "JavaScript", "CI/CD", "Automated Testing"],
    note: "This role has not been published yet.",
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Draft requisition for end-to-end web test automation suite setup.",
  },

  // -------------------------------------------------------------
  // CLOSED JOBS (3 Completed Hiring Roles)
  // -------------------------------------------------------------
  {
    id: "job-13",
    title: "UI Designer",
    company: "HireSmart AI",
    department: "Design",
    location: "Remote",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$115,000 - $140,000",
    applications: 86,
    matchScore: 91,
    status: "Closed",
    createdDate: "May 10, 2026",
    lastUpdated: "Jun 28, 2026",
    skills: ["Figma", "UI Components", "Design Systems", "Tokens"],
    note: "Hiring Completed • Offer Accepted",
    hiringManager: "Elena Rostova",
    recruiter: "Tanya Bhadana",
    aiSummary: "Requisition closed after candidate Elena Rostova accepted offer.",
  },
  {
    id: "job-14",
    title: "Technical Recruiter",
    company: "HireSmart AI",
    department: "Talent Acquisition",
    location: "San Francisco, CA",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$100,000 - $125,000",
    applications: 62,
    matchScore: 89,
    status: "Closed",
    createdDate: "Apr 15, 2026",
    lastUpdated: "Jun 15, 2026",
    skills: ["Sourcing", "Greenhouse", "LinkedIn Recruiter", "Interviewing"],
    note: "Hiring Completed • Offer Accepted",
    hiringManager: "Tanya Bhadana",
    recruiter: "Tanya Bhadana",
    aiSummary: "Position successfully filled for engineering talent acquisition team.",
  },
  {
    id: "job-15",
    title: "Business Analyst",
    company: "HireSmart AI",
    department: "Product",
    location: "Chicago, IL",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "3-5 Years",
    salaryRange: "$110,000 - $135,000",
    applications: 74,
    matchScore: 85,
    status: "Closed",
    createdDate: "May 01, 2026",
    lastUpdated: "Jun 20, 2026",
    skills: ["SQL", "Process Mapping", "Requirements Analysis", "Jira"],
    note: "Hiring Completed • Offer Accepted",
    hiringManager: "Jonathan Hayes",
    recruiter: "Tanya Bhadana",
    aiSummary: "Hiring completed for business analytics squad.",
  },

  // -------------------------------------------------------------
  // ARCHIVED JOBS (3 Historical Reference Roles)
  // -------------------------------------------------------------
  {
    id: "job-16",
    title: "Junior Python Developer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "Austin, TX",
    workType: "Onsite",
    employmentType: "Full-Time",
    experience: "1-2 Years",
    salaryRange: "$85,000 - $105,000",
    applications: 112,
    matchScore: 78,
    status: "Archived",
    createdDate: "Jan 12, 2026",
    lastUpdated: "Mar 30, 2026",
    skills: ["Python", "Django", "Git", "REST APIs"],
    note: "Archived requisition stored for reference.",
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    aiSummary: "Historical requisition archived following headcount restructuring.",
  },
  {
    id: "job-17",
    title: "Support Engineer",
    company: "HireSmart AI",
    department: "Operations",
    location: "Remote",
    workType: "Remote",
    employmentType: "Full-Time",
    experience: "2-3 Years",
    salaryRange: "$75,000 - $95,000",
    applications: 54,
    matchScore: 82,
    status: "Archived",
    createdDate: "Feb 05, 2026",
    lastUpdated: "Apr 10, 2026",
    skills: ["Zendesk", "SQL", "Customer Support", "Troubleshooting"],
    note: "Archived requisition stored for reference.",
    hiringManager: "Operations Lead",
    recruiter: "Tanya Bhadana",
    aiSummary: "Archived reference position from Q1 hiring cycle.",
  },
  {
    id: "job-18",
    title: "Sales Executive",
    company: "HireSmart AI",
    department: "Sales",
    location: "New York, NY",
    workType: "Onsite",
    employmentType: "Full-Time",
    experience: "4-6 Years",
    salaryRange: "$110,000 - $140,000",
    applications: 48,
    matchScore: 80,
    status: "Archived",
    createdDate: "Feb 20, 2026",
    lastUpdated: "May 05, 2026",
    skills: ["Enterprise Sales", "Salesforce", "B2B SaaS", "Outbound"],
    note: "Archived requisition stored for reference.",
    hiringManager: "Sales Director",
    recruiter: "Tanya Bhadana",
    aiSummary: "Archived sales requisition stored for future quota planning.",
  },
];

export const mockJobs12 = mockJobs18;

export const mockJobsWorkspace = {
  "job-1": {
    id: "job-1",
    title: "Senior Lead Frontend Engineer",
    company: "HireSmart AI",
    department: "Engineering",
    location: "San Francisco, CA (Hybrid)",
    workType: "Hybrid",
    employmentType: "Full-Time",
    experience: "5-7 Years",
    salaryRange: "$145,000 - $175,000",
    applications: 142,
    status: "Open",
    createdDate: "Jul 15, 2026",
    hiringManager: "Alex Mercer",
    recruiter: "Tanya Bhadana",
    description: "Architect high-performance React 19 micro-frontends and tokenized Tailwind CSS design systems.",
  },
};

export function getJobWorkspaceData(jobId) {
  const base = mockJobsWorkspace["job-1"];
  return {
    ...base,
    id: jobId,
    title: `Requisition ${jobId.replace("job-", "#")}`,
  };
}
