export const mockPipelineData = {
  // Top Executive KPIs
  stats: {
    totalPipelineCandidates: 1420,
    offersPending: 18,
    interviewsToday: 14,
    avgTimeToHireDays: 19,
    avgMatchScore: 89.2,
    hiringVelocity: "14 Days (Fast-Track)",
  },

  // Master 9 Pipeline Stages Metadata
  stageMetrics: {
    Applied: { title: "Applied", count: 480, avgDays: 2.1, dropRate: 15 },
    Screening: { title: "Screening", count: 290, avgDays: 3.4, dropRate: 22 },
    Assessment: { title: "Assessment", count: 185, avgDays: 4.2, dropRate: 18 },
    Technical: { title: "Technical", count: 160, avgDays: 5.1, dropRate: 28 },
    HR: { title: "HR Round", count: 95, avgDays: 2.8, dropRate: 12 },
    "Final Interview": { title: "Final Interview", count: 68, avgDays: 3.9, dropRate: 14 },
    Offer: { title: "Offer Extended", count: 32, avgDays: 4.5, dropRate: 8 },
    Hired: { title: "Hired", count: 85, avgDays: 18.0, dropRate: 0 },
    Rejected: { title: "Rejected", count: 225, avgDays: 6.2, dropRate: 100 },
  },

  // Company-wide Candidate Pool across 12 Open Jobs
  candidates: [
    {
      id: "cand-1",
      name: "Sarah Chen",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=160&auto=format&fit=crop",
      role: "Senior Lead Frontend Engineer",
      appliedJobId: "job-1",
      appliedJobTitle: "Senior Lead Frontend Engineer",
      department: "Engineering",
      location: "San Francisco, CA",
      experience: "6 Years",
      matchScore: 94,
      atsScore: 96,
      stage: "Technical",
      recruiter: "Tanya Bhadana",
      daysInStage: 3,
      priority: "High Match",
      interviewToday: true,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-2",
      name: "Marcus Vance",
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=160&auto=format&fit=crop",
      role: "Staff Frontend Architect",
      appliedJobId: "job-1",
      appliedJobTitle: "Senior Lead Frontend Engineer",
      department: "Engineering",
      location: "Oakland, CA",
      experience: "7 Years",
      matchScore: 92,
      atsScore: 94,
      stage: "Screening",
      recruiter: "Alex Mercer",
      daysInStage: 8,
      priority: "Stuck > 7 Days",
      interviewToday: false,
      needsReview: true,
      stuckTooLong: true,
    },
    {
      id: "cand-3",
      name: "Sophia Martinez",
      photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=160&auto=format&fit=crop",
      role: "React Tech Lead",
      appliedJobId: "job-1",
      appliedJobTitle: "Senior Lead Frontend Engineer",
      department: "Engineering",
      location: "San Jose, CA",
      experience: "6 Years",
      matchScore: 91,
      atsScore: 93,
      stage: "Final Interview",
      recruiter: "Tanya Bhadana",
      daysInStage: 2,
      priority: "Needs Action",
      interviewToday: true,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-4",
      name: "David Kim",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=160&auto=format&fit=crop",
      role: "Senior Backend Developer",
      appliedJobId: "job-2",
      appliedJobTitle: "Backend Engineer",
      department: "Engineering",
      location: "Austin, TX",
      experience: "5 Years",
      matchScore: 88,
      atsScore: 90,
      stage: "Assessment",
      recruiter: "Alex Mercer",
      daysInStage: 4,
      priority: "Standard",
      interviewToday: false,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-5",
      name: "Aisha Patel",
      photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=160&auto=format&fit=crop",
      role: "ML Engineer & NLP Lead",
      appliedJobId: "job-3",
      appliedJobTitle: "ML Engineer",
      department: "AI & Data",
      location: "New York, NY",
      experience: "5 Years",
      matchScore: 95,
      atsScore: 97,
      stage: "Offer",
      recruiter: "Tanya Bhadana",
      daysInStage: 5,
      priority: "Offer Pending",
      interviewToday: false,
      needsReview: true,
      stuckTooLong: false,
    },
    {
      id: "cand-6",
      name: "Elena Rostova",
      photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=160&auto=format&fit=crop",
      role: "DevOps Infrastructure Lead",
      appliedJobId: "job-5",
      appliedJobTitle: "DevOps Engineer",
      department: "Engineering",
      location: "Seattle, WA",
      experience: "6 Years",
      matchScore: 89,
      atsScore: 91,
      stage: "HR",
      recruiter: "Alex Mercer",
      daysInStage: 1,
      priority: "High Priority",
      interviewToday: false,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-7",
      name: "Jason Torres",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=160&auto=format&fit=crop",
      role: "Data Scientist",
      appliedJobId: "job-4",
      appliedJobTitle: "Data Scientist",
      department: "AI & Data",
      location: "Boston, MA",
      experience: "4 Years",
      matchScore: 84,
      atsScore: 86,
      stage: "Applied",
      recruiter: "Tanya Bhadana",
      daysInStage: 9,
      priority: "Stuck > 7 Days",
      interviewToday: false,
      needsReview: true,
      stuckTooLong: true,
    },
    {
      id: "cand-8",
      name: "Rachel Zhang",
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=160&auto=format&fit=crop",
      role: "Senior Product Manager",
      appliedJobId: "job-10",
      appliedJobTitle: "Product Manager",
      department: "Product",
      location: "New York, NY",
      experience: "7 Years",
      matchScore: 96,
      atsScore: 98,
      stage: "Offer",
      recruiter: "Tanya Bhadana",
      daysInStage: 2,
      priority: "Offer Pending",
      interviewToday: false,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-9",
      name: "Carlos Mendez",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=160&auto=format&fit=crop",
      role: "Cloud Security Architect",
      appliedJobId: "job-6",
      appliedJobTitle: "Cloud Engineer",
      department: "Engineering",
      location: "Denver, CO",
      experience: "5 Years",
      matchScore: 87,
      atsScore: 88,
      stage: "Assessment",
      recruiter: "Alex Mercer",
      daysInStage: 3,
      priority: "Standard",
      interviewToday: false,
      needsReview: false,
      stuckTooLong: false,
    },
    {
      id: "cand-10",
      name: "Emily Watson",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=160&auto=format&fit=crop",
      role: "AI Product Designer",
      appliedJobId: "job-11",
      appliedJobTitle: "UI/UX Designer",
      department: "Design",
      location: "Los Angeles, CA",
      experience: "5 Years",
      matchScore: 93,
      atsScore: 95,
      stage: "Hired",
      recruiter: "Tanya Bhadana",
      daysInStage: 14,
      priority: "Hired",
      interviewToday: false,
      needsReview: false,
      stuckTooLong: false,
    },
  ],

  // Recruitment Intelligence Engine Recommendations & Risk Indicators
  intelligence: {
    bottlenecks: [
      {
        stage: "Screening",
        issue: "28 candidates stuck > 7 days in Screening",
        explanation: "Alex Mercer has 18 unreviewed candidates for Backend Engineer role. Review SLA is exceeding target 48h.",
        impact: "High Attrition Risk (40% candidates interviewing elsewhere)",
        suggestedAction: "Reassign 10 screening tasks to Tanya Bhadana or send automated nudge.",
      },
      {
        stage: "Technical",
        issue: "Technical interview schedule lag (Avg 5.1 days)",
        explanation: "Engineering panel availability is constrained on Tuesdays & Thursdays.",
        impact: "Extends overall time-to-hire by 4 days",
        suggestedAction: "Add 2 secondary tech leads (David Miller & Sophia Martinez) to interviewer roster.",
      },
    ],

    weakApplicantJobs: [
      {
        jobTitle: "QA Engineer (Atlanta, GA)",
        avgScore: 74,
        explanation: "Incoming resume pool lacks Cypress automated testing skills; 65% are manual QA testers.",
        suggestedAction: "Update job title to 'Automated QA Engineer' and adjust LinkedIn sourcing keywords.",
      },
    ],

    fastMovingJobs: [
      { jobTitle: "Senior Lead Frontend Engineer", velocity: "9 Days Avg Stage Transition" },
      { jobTitle: "Product Manager", velocity: "11 Days Avg Stage Transition" },
    ],

    slowMovingJobs: [
      { jobTitle: "Data Scientist", velocity: "24 Days Avg Stage Transition (Bottleneck: Assessment)" },
      { jobTitle: "DevOps Engineer", velocity: "21 Days Avg Stage Transition (Bottleneck: Technical)" },
    ],

    riskIndicators: [
      { title: "2 Pending Offers Expiring Soon", detail: "Aisha Patel and Rachel Zhang offers expire in < 48 hours." },
      { title: "3 Top Candidates Interviewing Elsewhere", detail: "Marcus Vance and Sarah Chen hold active competing offers." },
    ],
  },

  // Audit Activity Stream
  activityStream: [
    { id: "act-101", user: "Tanya Bhadana", action: "Moved Aisha Patel to 'Offer Extended'", time: "10 mins ago", category: "offer" },
    { id: "act-102", user: "David Miller", action: "Completed 5.0 System Design evaluation for Sarah Chen", time: "1 hour ago", category: "interview" },
    { id: "act-103", user: "Alex Mercer", action: "Moved Marcus Vance to 'Screening'", time: "3 hours ago", category: "stage" },
    { id: "act-104", user: "HireSmart AI Engine", action: "Parsed 14 new candidates for Senior Lead Frontend Engineer", time: "5 hours ago", category: "upload" },
    { id: "act-105", user: "Sarah Jenkins", action: "Approved offer letter package for Rachel Zhang ($165k base)", time: "Yesterday", category: "offer" },
  ],
};
